AWSTemplateFormatVersion: 2010-09-09

Description: |
  EC2 instance for static web 

Parameters:

  ec2KeyPair:
    Description: Keypair keyname
    Type: AWS::EC2::KeyPair::KeyName
    

Resources:
  
  ec2sgMain:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow ssh and http # Required
      GroupName: tasha-carousel-sg
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  ec2instanceWebServer:
    Type: AWS::EC2::Instance
    Properties:
      Tags: 
      - Key: Name
        Value: tasha-webserver
    ImageId: ami-05ffe3c48a9991133
    InstanceType: t2.micro
    KeyName: !Ref ec2KeyPair
    SecurityGroupIds: 
      - !GetAtt ec2sgMain.GroupId
    UserData: string
    Fn::Base64:
      |
        #!/bin/bash -x

        dnf update -y
        dnf install httpd -y

        cd /var/www/html/

        FOLDER="https://raw.githubusercontent.com/TashaC1126/my-repository/refs/heads/main/101-kittens-carousel-static-website-ec2/static-web"

        wget ${FOLDER}/index.html
        wget ${FOLDER}/cat0.jpg
        wget ${FOLDER}/cat1.jpg
        wget ${FOLDER}/cat2.jpg

        systemctl start httpd
        systemctl enable httpd




#Outputs: